<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrt2fc0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrt2fc0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPrt2fc0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPrt2fc0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPrt2fc0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Prt2fc0',
    'container.build_id' => 'e61f5b7a',
    'container.build_time' => 1524648723,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrt2fc0');
